<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>VerifyShopify</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4849e2fd-4f80-46ac-85f8-a3b6e7a42aa7</testSuiteGuid>
   <testCaseLink>
      <guid>216c6227-e8b0-42ef-ab9c-6d474f64c1e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopify/TC04_Open login shopify page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a5ae0aca-4dbf-490a-a01a-55c87a5fd845</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopify/TC01_Login Shopify</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>967801f7-abd8-4dba-a7f5-39565441d66d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae944752-ba6b-4721-8bed-2f9bd2f6dd69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d64aa1c0-bd89-41b2-9302-61453c1be041</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47c681dc-80f0-4f1f-88c7-8e27f8bd5f0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9001f4ec-55e3-4fc9-a0f2-95276b97294d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80ca749a-1aee-44af-a3ae-03574470ae9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopify/TC02_Create a store</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c8807cbb-65ae-4b86-93b5-32c38921c881</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-5</value>
         </iterationEntity>
         <testDataId>Data Files/Shopify</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c8807cbb-65ae-4b86-93b5-32c38921c881</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>store_name</value>
         <variableId>be254344-4714-4c53-b5a1-788e24d97d6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19b7dcad-8591-4c1c-9d0e-7149056e8a4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76b5c588-9f41-484e-b78c-7e8a00511a44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5775480a-e610-4c3a-a160-f981e6033d8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36f02f7e-193d-4867-ae14-fd84b2cfe250</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bf3a982-5969-4071-b52b-e74ff4291fda</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopify/TC03_Install AR App</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37bf1e56-8b33-4f5e-ad48-9a27531f9426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e873310d-e654-40b1-b39a-6ef7bf034b16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96f2dccc-1426-4b3b-bd8f-afd4653391c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cacc7717-196e-4ddd-98f2-e893dad1e5f3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
